In [1]:
import os
import GEOparse
import pandas as pd

# Get GEO_ID from parent folder name
GEO_ID = os.path.basename(os.path.dirname(os.path.abspath('__file__')))

gse = GEOparse.get_GEO(geo=GEO_ID, silent=True)

# map sample title to metadata
metadata = {}

for key, value in gse.gsms.items():
    sample_title = value.metadata['title'][0]

    metadata_object = {'sample_title': sample_title}
    for item in value.metadata['characteristics_ch1']:
        k, v = item.split(':')
        metadata_object[k.strip()] = v.strip()

    metadata[key] = metadata_object


metadata_df = pd.DataFrame.from_dict(metadata, orient='index')
metadata_df.index.name = 'samples'

metadata_df

,sample_title,tissue,disease,survival (months),status alive_(0)/dead_(1)
samples,,,,,
GSM6779143,"GB, Patient_1",Glioma surgical sample,GB,14,1
GSM6779144,"LGG, Patient_1",Glioma surgical sample,LGG,25,0
GSM6779145,"GB, Patient_2",Glioma surgical sample,GB,14,1
GSM6779146,"GB, Patient_3",Glioma surgical sample,GB,8,1
GSM6779147,"GB, Patient_4",Glioma surgical sample,GB,17,1
GSM6779148,"GB, Patient_5",Glioma surgical sample,GB,16,0
GSM6779149,"LGG, Patient_2",Glioma surgical sample,LGG,112,0
GSM6779150,"LGG, Patient_3",Glioma surgical sample,LGG,111,0
GSM6779151,"LGG, Patient_4",Glioma surgical sample,LGG,104,0
GSM6779152,"LGG, Patient_5",Glioma surgical sample,LGG,39,1
GSM6779153,"GB, Patient_6",Glioma surgical sample,GB,9,1
GSM6779154,"GB, Patient_7",Glioma surgical sample,GB,15,1
GSM6779155,"GB, Patient_8",Glioma surgical sample,GB,1,1
GSM6779156,"GB, Patient_9",Glioma surgical sample,GB,13,1
GSM6779157,"GB, Patient_10",Glioma surgical sample,GB,72,1
GSM6779158,"GB, Patient_11",Glioma surgical sample,GB,1,1
GSM6779159,"GB, Patient_12",Glioma surgical sample,GB,9,1
GSM6779160,"GB, Patient_13",Glioma surgical sample,GB,4,1
GSM6779161,"GB, Patient_14",Glioma surgical sample,GB,8,1
GSM6779162,"GB, Patient_15",Glioma surgical sample,GB,7,1
GSM6779163,"GB, Patient_16",Glioma surgical sample,GB,8,1
GSM6779164,"GB, Patient_17",Glioma surgical sample,GB,8,1
GSM6779165,"LGG, Patient_6",Glioma surgical sample,LGG,102,0
GSM6779166,"LGG, Patient_7",Glioma surgical sample,LGG,95,1
GSM6779167,"LGG, Patient_8",Glioma surgical sample,LGG,41,1
GSM6779168,"LGG, Patient_9",Glioma surgical sample,LGG,87,0
GSM6779169,"Healthy_Brain, Control",Normal Brain,Healthy,-,-

In [2]:
supplementary_data_url = "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE219250&format=file&file=GSE219250%5FNAT%5Flnc%2Ecsv%2Egz"

expression_data_df = pd.read_csv(supplementary_data_url, compression="gzip", sep=";")

In [3]:
expression_data_df

,run10_301251_tpm_lnc,run10_311687_tpm_lnc,run11_295604_tpm_lnc,run11_303989_tpm_lnc,run11_304627_tpm_lnc,run11_332058_tpm_lnc,run12_102940_tpm_lnc,run12_200189_tpm_lnc,run12_208673_tpm_lnc,run12_227728_tpm_lnc,...,external_gene_name_mRNA,chromosome_name_mRNA,start_position_mRNA,end_position_mRNA,strand_mRNA,transcript_start_mRNA,transcript_end_mRNA,transcription_start_site_mRNA,transcript_length_mRNA,mRNA_transcript_version_mRNA
0,NaN,9.372247,NaN,NaN,NaN,NaN,NaN,NaN,14.313933,NaN,...,ACSL6,5,131949973.0,132012243.0,-1.0,131953957.0,132011626.0,132011626.0,2483.0,9
1,NaN,9.372247,NaN,NaN,4.438231,NaN,NaN,NaN,NaN,NaN,...,ADARB2,10,1177313.0,1737525.0,-1.0,1177313.0,1737525.0,1737525.0,8475.0,6
2,NaN,NaN,46.672579,6.130062,8.876462,NaN,NaN,NaN,NaN,NaN,...,BAALC,8,103140713.0,103230305.0,1.0,103140759.0,103228218.0,103140759.0,801.0,6
3,NaN,NaN,6.667511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,BAALC,8,103140713.0,103230305.0,1.0,103140759.0,103228218.0,103140759.0,801.0,6
4,NaN,NaN,6.667511,NaN,4.438231,NaN,NaN,NaN,NaN,13.104958,...,BAALC,8,103140713.0,103230305.0,1.0,103140759.0,103228218.0,103140759.0,801.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,TENM4,11,78652829.0,79441030.0,-1.0,78652829.0,79441030.0,79441030.0,14381.0,12
164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,GALNT18,11,11270877.0,11622005.0,-1.0,11270877.0,11622005.0,11622005.0,2503.0,5
165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,PPM1A,14,60245752.0,60299087.0,1.0,60245752.0,60292731.0,60245752.0,1713.0,7
166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,GALNT9,12,132196372.0,132329589.0,-1.0,132196372.0,132329589.0,132329589.0,2933.0,13
167,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,GALNT9,12,132196372.0,132329589.0,-1.0,132196372.0,132329589.0,132329589.0,2933.0,13