In [1]:
import os
import GEOparse 
import pandas as pd


# Get GEO_ID from parent folder name
GEO_ID = os.path.basename(os.path.dirname(os.path.abspath('__file__')))

gse = GEOparse.get_GEO(geo=GEO_ID, silent=True)

# map sample title to metadata
metadata = {}

for key, value in gse.gsms.items():
    sample_title = value.metadata['title'][0]

    metadata_object = {}
    for item in value.metadata['characteristics_ch1']:
        k, v = item.split(':')
        metadata_object[k.strip()] = v.strip()

    metadata[sample_title] = metadata_object


# Create metadata DataFrame and join as columns to df_genes (rows=samples)
metadata_df = pd.DataFrame.from_dict(metadata, orient='index')
metadata_df.index.name = 'samples'
# Remove rows where index contains "repl" suffix (technical replicates)
metadata_df = metadata_df[~metadata_df.index.str.contains('repl$')]
metadata_df.head()

,scan-b external id,instrument model,age at diagnosis,tumor size,lymph node group,lymph node status,er status,pgr status,her2 status,ki67 status,...,nhg prediction mgc,er prediction sgc,pgr prediction sgc,her2 prediction sgc,ki67 prediction sgc,pam50 subtype,overall survival days,overall survival event,endocrine treated,chemo treated
samples,,,,,,,,,,,,,,,,,,,,,
F1,Q008818.C008840.S000215.l.r.m2.c.lib.g.k.a.t,HiSeq 2000,43,9,NodeNegative,NodeNegative,NA,NA,0,NA,...,G3,0,0,0,1,Basal,2367,0,0,1
F2,Q008769.C008792.S000250.l.r.m.c.lib.g.k.a.t,HiSeq 2000,48,14,1to3,NodePositive,1,1,0,NA,...,G2,1,1,0,0,LumA,2367,0,1,1
F3,Q008568.C008577.S000424.l.r.m3.c.lib.g.k.a.t,HiSeq 2000,69,27,4toX,NodePositive,1,1,0,NA,...,G3,1,1,0,1,LumB,2168,1,1,1
F4,Q008909.C009000.S000084.l.r.m.c.lib.g.k.a.t,HiSeq 2000,39,51,1to3,NodePositive,1,NA,1,NA,...,G3,1,1,1,1,LumA,2416,0,1,1
F5,Q008781.C008782.S000260.l.r.m.c.lib.g.k.a.t,HiSeq 2000,73,60,4toX,NodePositive,1,NA,0,NA,...,G2,1,1,0,0,Normal,2389,0,1,0

In [2]:
# the file is large so we saved it locally. 
# Here is the download URL: https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE96058&format=file&file=GSE96058%5Fgene%5Fexpression%5F3273%5Fsamples%5Fand%5F136%5Freplicates%5Ftransformed%2Ecsv%2Egz
df = pd.read_csv('GSE96058_gene_expression_3273_samples_and_136_replicates_transformed.csv.gz', index_col=0) 
df = df.T
df = df[~df.index.str.contains('repl$')]


data_file_name = f'{GEO_ID}_original.csv'
df = metadata_df.join(df, how='inner')
df.reset_index(inplace=True)
df = df.rename(columns={'index': 'samples'})
df.to_csv(data_file_name, index=False)

In [3]:
df

,samples,scan-b external id,instrument model,age at diagnosis,tumor size,lymph node group,lymph node status,er status,pgr status,her2 status,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
0,F1,Q008818.C008840.S000215.l.r.m2.c.lib.g.k.a.t,HiSeq 2000,43,9,NodeNegative,NodeNegative,NA,NA,0,...,1.108204,3.044573,1.640598,2.425306,3.244432,-0.411950,1.468899,6.281767,1.774107,2.437227
1,F2,Q008769.C008792.S000250.l.r.m.c.lib.g.k.a.t,HiSeq 2000,48,14,1to3,NodePositive,1,1,0,...,1.678388,2.743902,0.684370,1.861781,2.727427,-0.452902,1.924761,7.169613,1.764214,2.876100
2,F3,Q008568.C008577.S000424.l.r.m3.c.lib.g.k.a.t,HiSeq 2000,69,27,4toX,NodePositive,1,1,0,...,2.443392,4.719843,-0.160076,1.365396,3.122333,0.594147,1.619277,6.683400,2.039246,2.929346
3,F4,Q008909.C009000.S000084.l.r.m.c.lib.g.k.a.t,HiSeq 2000,39,51,1to3,NodePositive,1,NA,1,...,2.441704,4.157466,1.036271,2.038984,3.182823,-0.046619,1.969433,6.666306,2.771650,2.777674
4,F5,Q008781.C008782.S000260.l.r.m.c.lib.g.k.a.t,HiSeq 2000,73,60,4toX,NodePositive,1,NA,0,...,1.749230,1.024820,1.147535,2.032704,3.588842,0.808823,2.998474,6.479006,2.696269,3.957146
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3268,F3269,Q002592.C002615.S006749.l.r.m.c.lib.g.k.a.t,HiSeq 2000,72,13,NodeNegative,NodeNegative,1,1,0,...,2.752051,4.113655,0.981655,2.970771,3.552432,-0.104050,2.637901,5.894652,3.103157,4.051229
3269,F3270,Q002587.C002614.S006769.l.r.m.c.lib.g.k.a.t,HiSeq 2000,69,30,1to3,NodePositive,1,1,0,...,1.717592,3.568886,0.966792,2.239092,3.244217,-1.672000,2.352732,6.328234,2.751821,3.507546
3270,F3271,Q002595.C002613.S006751.l.r.m.c.lib.g.k.a.t,NextSeq 500,73,18,NodeNegative,NodeNegative,1,0,NA,...,2.432033,3.830811,0.525307,1.623993,3.005552,0.648627,2.254223,6.038816,2.962222,2.258526
3271,F3272,Q002539.C002577.S006770.l.r.m.c.lib.g.k.a.t,HiSeq 2000,67,33,1to3,NodePositive,1,1,0,...,1.462764,2.809853,0.602305,1.944311,2.700106,-0.422385,2.339483,6.024796,1.931844,2.909847
3272,F3273,Q002531.C002576.S006771.l.r.m.c.lib.g.k.a.t,NextSeq 500,60,17,1to3,NodePositive,1,1,0,...,2.189862,3.625292,0.617938,2.037576,2.811346,-1.771027,2.349290,6.147887,1.804658,3.499754

# Generate description

In [4]:
import json
import os
import sys
from pathlib import Path

project_root = Path().resolve().parent.parent  # adjust based on notebook depth
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from geo.scripts.generate_descriptions import generate_description_from_geo

description_file_path = 'description.json'

if not os.path.exists(description_file_path):
    with open(description_file_path, 'w') as f:
        json.dump({}, f)

with open(description_file_path, 'r') as f:
    desc_data = json.load(f)

if not desc_data:
    desc_data = generate_description_from_geo(GEO_ID, limit_samples=10)
    print("Description generated")

desc_data['data_summary'] = {
    'samples': metadata_df.reset_index().shape[0],
    'clinical_features': metadata_df.reset_index().shape[1],
    'genes': df.shape[1]
}

print("Description updated")

desc_data['data_file_names'] = [data_file_name]

with open(description_file_path, "w") as f:
    json.dump(desc_data, f,ensure_ascii=False, indent=4)

Description updated