In [1]:
import os
import GEOparse
import pandas as pd

# Get GEO_ID from parent folder name
GEO_ID = os.path.basename(os.path.dirname(os.path.abspath('__file__')))

gse = GEOparse.get_GEO(geo=GEO_ID, silent=True)

# map sample title to metadata
metadata = {}

for key, value in gse.gsms.items():
    sample_title = value.metadata['title'][0]

    metadata_object = {'sample_title': sample_title}
    for item in value.metadata['characteristics_ch1']:
        k, v = item.split(':')
        metadata_object[k.strip()] = v.strip()

    metadata[key] = metadata_object


metadata_df = pd.DataFrame.from_dict(metadata, orient='index')
metadata_df.index.name = 'samples'

metadata_df

               sample_title            cell type
samples
GSM5688738  X1277013_BA.TPM              bladder
GSM5688739  X1375590_BA.TPM              bladder
GSM5688740  X1442434_BA.TPM              bladder
GSM5688741  X1443189_BA.TPM              bladder
GSM5688742  X1443723_BA.TPM              bladder
...                     ...                  ...
GSM5688811    tpm_CA1586932  bladder cancer cell
GSM5688812    tpm_CA1587363  bladder cancer cell
GSM5688813    tpm_CA1589480  bladder cancer cell
GSM5688814    tpm_CA1589810  bladder cancer cell
GSM5688815    tpm_CA1590649  bladder cancer cell

[70 rows x 2 columns]

### Metadata from GEO is unnecessary here. All the information is provided in the supplementary data.

In [2]:
# supplementary data located here: https://pmc.ncbi.nlm.nih.gov/articles/instance/8718409/bin/Table_1.xlsx

expression_data_df = pd.read_excel('Table_1.xlsx', skiprows=1, sheet_name=2)
expression_data_df = expression_data_df.rename(columns={'ID': 'gene_symbol'})
expression_data_df = expression_data_df.set_index('gene_symbol')
expression_data_df = expression_data_df.T
expression_data_df.index.name = 'sample_title'

In [3]:
clinical_data_df = pd.read_excel('Table_1.xlsx', skiprows=1, sheet_name=1)
clinical_data_df = clinical_data_df.rename(columns={'Patient.number': 'sample_title'})
clinical_data_df = clinical_data_df.set_index('sample_title')

# clinical_data_df['Overall survival time'] = clinical_data_df['Overall survival time'].str.replace('survival day:', '', regex=False).str.strip()
# clinical_data_df['Overall survival status'] = clinical_data_df['Overall survival status'].str.replace('overall survival: ', '', regex=False).str.strip()

df_combined = clinical_data_df.merge(
    expression_data_df,
    left_on='sample_title',
    right_on='sample_title',
    how='inner'
)

# Drop accidental date-like feature columns introduced from source headers.
df_combined = df_combined.loc[:, pd.to_datetime(df_combined.columns, errors='coerce').isna()]


data_file_name = f'{GEO_ID}_original.csv'
df_combined.to_csv(data_file_name, index=True)
df_combined

/var/folders/h1/fnfx16m50jvd8ddpcs93g9mw0000gn/T/ipykernel_2302/3742391447.py:16: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_combined = df_combined.loc[:, pd.to_datetime(df_combined.columns, errors='coerce').isna()]

,Age,Sex,Overall survival time,Overall survival status,Grade,Pathological Stage,Muscular_infiltration,FLT3LG,ERI1,SAP130,...,SLC10A3,TMEM141,ASPN,ZAN,RAB6A,PDPR,OR5B12,ST3GAL4,ZNF428,HIGD1A
sample_title,,,,,,,,,,,,,,,,,,,,,
tpm_CA1277013,58,Female,survival day: 377,overall survival: death,High,T4N0M0,MIBC,2.23,5.45,11.33,...,20.75,133.33,2.73,0.13,57.89,7.85,0.00,23.39,24.84,33.17
tpm_CA1308866,50,male,survival day:1518,overall survival: survival,High,T2N1M0,MIBC,17.90,5.56,21.74,...,70.66,93.95,4.14,0.00,104.52,13.68,0.00,105.12,29.61,92.48
tpm_CA1315330,63,male,survival day:946,overall survival: survival,High,T1NOMO,NMIBC,6.16,17.38,18.86,...,43.94,49.03,0.52,0.00,91.05,4.58,0.00,362.63,31.69,85.21
tpm_CA1366278,53,male,survival day:1258,overall survival: survival,High,T1NOMO,NMIBC,27.50,4.57,11.14,...,43.40,63.97,0.78,0.00,62.86,7.81,0.00,167.51,29.94,53.33
tpm_CA1375590,46,male,survival day:1213,overall survival: survival,High,T3bN1M0,MIBC,13.15,3.98,19.92,...,16.72,162.90,33.68,0.00,105.01,10.13,0.00,24.21,74.77,102.17
tpm_CA1382793,72,Female,survival day:1192,overall survival: survival,Low,T1N0M0,NMIBC,16.06,5.52,11.35,...,42.14,124.46,0.73,0.00,59.53,12.04,0.00,253.64,34.04,51.78
tpm_CA1409255,69,Female,survival day:1047,overall survival: survival,High,T3NOMO,MIBC,16.59,4.12,11.41,...,49.43,63.27,0.63,0.00,58.39,11.01,0.00,16.79,37.75,57.68
tpm_CA1427893,60,male,survival day:970,overall survival: survival,High,T1NOMO,NMIBC,15.62,1.85,6.77,...,41.87,82.72,0.94,0.00,60.66,2.63,0.00,209.48,12.39,90.64
tpm_CA1430225,57,male,survival day: 443,overall survival: death,High,T3NOMO,MIBC,13.44,2.19,11.45,...,57.70,121.90,0.46,0.00,76.63,7.37,0.00,50.25,22.14,99.70
tpm_CA1435228,70,male,survival day:975,overall survival: survival,Low,T1NOMO,NMIBC,4.76,4.48,16.26,...,60.66,81.75,1.01,0.00,68.78,7.49,0.00,414.19,32.38,151.96
tpm_CA1436303,54,male,survival day: 877,overall survival: death,High,T1NOMO,NMIBC,28.28,4.47,13.00,...,38.53,50.12,12.39,0.00,88.34,16.62,0.00,41.98,46.92,71.23
tpm_CA1442434,61,male,survival day:911,overall survival: survival,High,T1N0M0,NMIBC,23.48,4.08,12.97,...,32.09,34.33,3.78,0.00,72.65,15.78,0.00,35.46,50.42,70.89
tpm_CA1443189,67,male,survival day:914,overall survival: survival,High,T2NOMO,MIBC,26.55,11.47,16.80,...,62.98,102.49,5.36,0.00,86.49,5.36,0.00,61.59,21.97,54.34
tpm_CA1443723,62,male,survival day: 662,overall survival: death,High,T3NOMO,MIBC,16.81,8.16,18.69,...,43.92,84.64,18.40,0.01,162.92,10.44,0.00,110.13,25.83,73.30
tpm_CA1445125,55,male,survival day:905,overall survival: survival,High,T1N0M0,NMIBC,14.33,1.83,10.73,...,42.65,47.07,0.13,0.00,46.00,13.31,0.00,175.76,32.77,78.22
tpm_CA1455582,66,male,survival day: 423,overall survival: death,High,T2aN0M0,MIBC,14.11,9.16,13.65,...,71.29,99.21,1.22,0.00,132.63,18.61,0.00,40.31,51.69,53.29
tpm_CA1456349,66,male,survival day:851,overall survival: survival,High,T1N0M0,NMIBC,9.13,3.51,9.51,...,52.00,94.43,1.53,0.00,61.22,6.43,0.00,166.35,32.71,50.02
tpm_CA1456774,45,male,survival day:876,overall survival: survival,High,T4N0M0,MIBC,18.14,13.53,21.21,...,65.70,132.68,1.17,0.00,114.99,21.81,0.00,200.27,50.82,117.16
tpm_CA1460006,71,male,survival day:857,overall survival: survival,High,T2N0M0,MIBC,29.98,7.16,12.72,...,51.77,82.93,18.92,0.02,134.61,13.10,0.00,42.48,24.61,56.52
tpm_CA1461830,74,male,survival day:807,overall survival: survival,High,T3bN1M0,MIBC,9.41,5.30,17.93,...,41.73,201.13,8.97,0.00,58.02,9.66,0.00,35.96,29.78,54.70
tpm_CA1463949,63,male,survival day: 797,overall survival: death,High,T4N0M0,MIBC,22.01,6.01,13.34,...,46.87,51.25,21.71,0.00,104.19,23.36,0.00,48.43,37.75,81.36
tpm_CA1466950,62,Female,survival day: 766,overall survival: death,High,T2N0M0,MIBC,12.38,4.53,13.24,...,52.65,129.42,6.08,0.00,144.97,6.73,0.00,62.44,25.98,142.03
tpm_CA1473520,55,male,survival day:781,overall survival: survival,Low,T1NOMO,NMIBC,29.16,8.96,14.84,...,34.80,105.68,5.20,0.00,92.72,10.98,0.00,108.60,33.41,125.38
tpm_CA1474704,59,male,survival day:881,overall survival: survival,High,T4NOM0,MIBC,23.26,8.27,8.14,...,49.99,32.99,2.64,0.00,99.99,11.01,0.11,195.30,36.42,47.49
tpm_CA1474792,70,male,survival day:797,overall survival: survival,High,T4N1M0,MIBC,14.53,14.85,20.16,...,89.33,90.94,1.11,0.00,119.58,10.13,0.00,503.69,20.54,79.32
tpm_CA1481528,54,male,survival day:736,overall survival: survival,High,T1NOM0,NMIBC,1.99,11.27,10.94,...,24.02,103.85,1.14,0.00,114.78,9.04,0.00,226.77,22.05,74.33
tpm_CA1481665,69,male,survival day:736,overall survival: survival,High,T2N0M0,MIBC,6.79,8.86,11.83,...,118.95,94.17,0.82,0.00,200.98,9.38,0.10,20.41,33.24,151.67
tpm_CA1485034,73,male,survival day:859,overall survival: survival,High,T2bN0M0,MIBC,10.19,7.68,15.16,...,63.34,116.14,0.90,0.00,99.36,44.72,0.00,258.50,19.92,59.70
tpm_CA1501158,75,male,survival day:659,overall survival: survival,P,T0N0M0,NMIBC,38.44,5.95,11.27,...,41.20,104.72,6.85,0.00,60.95,12.21,0.08,91.67,45.50,54.41
tpm_CA1502091,77,male,survival day: 671,overall survival: death,High,T3N1M0,MIBC,27.77,5.19,11.55,...,38.23,36.40,28.75,0.00,79.64,15.66,0.09,45.46,41.78,81.78
tpm_CA1502698,50,Female,survival day:689,overall survival: survival,High,T3N0M0,MIBC,9.52,2.76,17.65,...,60.34,79.36,0.89,0.22,68.46,6.20,0.00,25.08,10.01,39.92
tpm_CA1503628,66,male,survival day:645,overall survival: survival,Low,T1N0M0,NMIBC,11.94,7.23,18.35,...,55.56,46.11,0.33,0.00,125.91,15.68,0.00,400.37,28.18,90.98
tpm_CA1505257,77,Female,survival day:653,overall survival: survival,High,T3N0M0,MIBC,29.12,7.86,15.06,...,41.38,93.06,2.07,0.00,63.62,8.12,0.00,27.80,32.94,28.67
tpm_CA1505875,60,male,survival day:646,overall survival: survival,High,T1N0M0,NMIBC,10.23,8.61,19.88,...,46.30,94.60,3.77,0.00,100.66,9.08,0.00,39.87,45.57,118.03
tpm_CA1506424,70,male,survival day:622,overall survival: survival,High,T2N0M0,MIBC,23.16,5.46,9.92,...,58.27,21.59,0.93,0.04,53.02,10.72,0.00,274.52,29.50,38.02
tpm_CA1510351,60,male,survival day: 147,overall survival: death,High,T3N0M0,MIBC,28.38,4.44,13.87,...,35.23,81.60,23.81,0.00,116.91,15.67,0.10,27.52,50.70,179.75
tpm_CA1511992,80,male,survival day:972,overall survival: survival,High,T3N0M0,MIBC,27.21,7.33,21.82,...,45.70,63.31,46.20,0.00,84.46,14.74,0.00,55.19,54.52,66.57
tpm_CA1513247,66,male,survival day:606,overall survival: survival,High,T2bN0M0,MIBC,31.30,6.98,10.04,...,44.12,46.38,14.37,0.00,73.99,13.79,0.00,41.72,34.23,70.37
tpm_CA1517987,77,male,survival day:592,overall survival: survival,Low,T1N0M0,NMIBC,17.71,5.72,11.94,...,44.29,95.69,0.26,0.01,49.86,15.36,0.00,161.08,43.99,35.56
tpm_CA1521373,83,male,survival day:565,overall survival: survival,Low,T1N0M0,NMIBC,13.48,6.42,16.54,...,27.03,92.11,0.61,0.00,87.14,20.48,0.00,42.66,36.53,77.23
tpm_CA1522117,73,male,survival day:592,overall survival: survival,Low,T1N0M0,NMIBC,15.37,5.61,15.49,...,26.24,105.94,2.12,0.00,87.21,38.28,0.00,255.01,29.37,79.47
tpm_CA1526051,70,male,survival day:549,overall survival: survival,High,T2N0M0,MIBC,55.71,4.45,12.25,...,76.52,150.75,17.48,0.37,127.08,8.17,0.09,19.92,18.89,42.17
tpm_CA1528542,33,male,survival day:556,overall survival: survival,Low,T1N0M0,NMIBC,9.65,6.04,13.30,...,56.30,101.61,0.38,0.01,82.07,9.39,0.00,197.54,29.63,80.72
tpm_CA1532452,45,male,survival day:526,overall survival: survival,High,T4N0M0,MIBC,17.66,20.69,13.99,...,25.73,54.40,4.41,0.00,80.29,11.61,0.00,47.00,71.73,34.21
tpm_CA1533024,56,male,survival day:523,overall survival: survival,High,T4N0M1,MIBC,22.83,7.03,12.13,...,48.85,180.10,3.20,0.00,67.55,15.13,0.00,9.03,26.08,38.75
tpm_CA1534929,64,male,survival day:534,overall survival: survival,High,T2N0M1,MIBC,19.65,4.84,17.41,...,37.23,40.08,15.41,0.00,112.74,24.88,0.00,44.86,42.41,85.80
tpm_CA1554315,65,Female,survival day: 239,overall survival: death,High,T3aN1M1,MIBC,53.80,8.16,13.48,...,32.30,67.11,54.04,0.00,71.58,9.12,0.00,30.58,46.38,50.86
tpm_CA1559012,78,male,survival day: 299,overall survival: death,High,T2bN0M0,MIBC,26.87,4.14,13.36,...,52.10,111.55,7.97,0.00,90.78,24.28,0.00,118.11,34.14,61.86
tpm_CA1568599,67,Female,survival day:725,overall survival: survival,Low,T1N0M0,NMIBC,9.60,11.05,14.75,...,42.67,231.69,1.02,0.00,71.63,14.49,0.00,747.30,18.47,103.41
tpm_CA1580755,71,male,survival day: 159,overall survival: death,High,T4N0M1,MIBC,18.02,11.81,23.49,...,56.86,40.16,0.95,0.09,101.81,15.62,0.10,76.75,46.99,105.76
tpm_CA1586396,62,male,survival day:235,overall survival: survival,Low,T1N0M0,NMIBC,26.00,5.55,13.84,...,43.49,138.52,0.08,0.00,76.94,27.94,0.00,53.72,31.33,61.10
tpm_CA1586932,65,male,survival day:240,overall survival: survival,P,T0N0M0,NMIBC,33.04,3.73,12.85,...,45.81,219.78,0.56,0.00,57.05,18.99,0.00,73.35,42.60,51.61
tpm_CA1587363,51,male,survival day:230,overall survival: survival,High,T1N0M0,NMIBC,30.62,10.96,14.21,...,57.06,87.23,0.50,0.00,97.05,12.23,0.00,244.91,30.75,75.65
tpm_CA1589480,71,male,survival day:204,overall survival: survival,Low,T0N0M0,NMIBC,17.70,4.99,11.31,...,40.71,106.85,1.00,0.00,78.94,15.13,0.00,130.08,33.37,43.17
tpm_CA1589810,66,Female,survival day:242,overall survival: survival,High,T4N0M1,MIBC,6.73,5.63,14.47,...,63.59,147.19,1.58,0.00,108.20,8.75,0.00,89.38,42.53,82.21
tpm_CA1590649,64,Female,survival day:226,overall survival: survival,Low,T2N0M0,MIBC,8.43,1.84,10.68,...,38.29,132.51,1.77,0.09,77.84,4.77,0.00,5.53,8.72,38.33
tpm_CA1520663,lost to follow-up,NaN,NaN,NaN,NaN,NaN,NaN,11.16,4.33,14.89,...,48.05,91.95,0.99,0.00,98.38,9.52,0.00,186.97,34.00,71.85

In [4]:
'2021-09-06 00:00:00' in df_combined.columns

False

In [5]:
clinical_data_df.to_csv(f'{GEO_ID}_clinical_data.csv', index=True)

# Generate description

In [6]:
import json
import os
import sys
from pathlib import Path

project_root = Path().resolve().parent.parent  # adjust based on notebook depth
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from geo.scripts.generate_descriptions import generate_description_from_supplement

description_file_path = 'description.json'

if not os.path.exists(description_file_path):
    with open(description_file_path, 'w') as f:
        json.dump({}, f)

with open(description_file_path, 'r') as f:
    desc_data = json.load(f)

if not desc_data:
    desc_data = generate_description_from_supplement(GEO_ID, 'GSE188715_clinical_data.csv')
    print("Description generated")

desc_data['data_summary'] = {
     'samples': clinical_data_df.shape[0],
    'clinical_features': clinical_data_df.reset_index().shape[1],
    'genes': expression_data_df.shape[1]
}

print("Description updated")

desc_data['data_file_names'] = [data_file_name]

with open(description_file_path, "w") as f:
    json.dump(desc_data, f, indent=4)

Description updated